-- 'CODE_AGENCE', 'NUMERO_POLICE', 'NOTE_COUVERTURE', 'CODE_BRANCHE', 'CODE_SOUS_BRANCHE', 'CODE_CLIENT', 'ASSURE', 'TYPE_TARIFICATION', 'CODE_AVENANT', 'NUM_AVNT_COURS', 'FRAIS', 'TAXES', 'DATE_SOUSCRIPTION_POLICE', 'DATE_EFFET_POLICE', 'DATE_SOUSCRIPTION', 'DATE_EFFET', 'DATE_ECHEANCE_PRINCIPALE', 'DATE_ECHEANCE_PROCHAINE', 'DATE_EXPIRATION', 'DATE_DERN_MAJ', 'DATE_COMPTANT_DU', 'DATE_COMPTANT_AU', 'CODE_FONCTIONNEMENT', 'TERME', 'CODE_FRACTIONNEMENT', 'COASSURANCE', 'TYPE_COASSURANCE', 'NBR_COASSUREURS', 'TAUX_COASSURANCE', 'FRAIS_COASSURANCE', 'TAUX_COMMISSION_DEROGATOIRE_BASE', 'TAUX_COMMISSION_DEROGATOIRE_ANNEXE', 'COMMISSION_BASE_ANN', 'COMMISSION_ANNEXE_ANN', 'COMMISSION_ANN', 'COMMISSION_BASE_COMPTANT', 'COMMISSION_ANNEXE_COMPTANT', 'COMMISSION_COMPTANT', 'PRIME_ANN_GBASE', 'PRIME_ANN_GANNEXE', 'FRAIS_ANN', 'TAXES_ANN_BASE', 'TAXES_ANN_ANNEXE', 'TAXES_ANN', 'PRIME_TOTAL_ANN', 'PRIME_COMPTANT_GBASE', 'PRIME_COMPTANT_GANNEXE', 'FRAIS_COMPTANT', 'TAXES_COMPTANT_BASE', 'TAXES_COMPTANT_ANNEXE', 'TAXES_COMPTANT', 'PRIME_TOTAL_COMPTANT', 'NUMERO_PROPOSITION', 'TYPE', 'NOM', 'PRENOM', 'RAISON_SOC', 'PAYS', 'VILLE', 'ADRESSE', 'CP_VILLE', 'TEL', 'GSM', 'FAX', 'E_MAIL', 'PROFESSION', 'SEC_ACTIVITE', 'CIN', 'REG_COMMERCE', 'CODE_TVA', 'ABREVIATION', 'RIB', 'CODE_CLIENT_RGP', 'CODE_NEW', 'VIP', 'IMMATRICULATION', 'MARQUE_VEHICULE', 'TYPE_VEHICULE', 'CODE_SUSPENTION', 'DATE_SUSPENTION', 'CODE_REM_VIGUEUR', 'DATE_REM_VIGUEUR', 'CODE_RESILIATION', 'DATE_RESILIATION', 'CODE_REM_COURS', 'DATE_REM_COURS', 'CODE_REASSURANCE', 'BONUS_MALUS', 'COMMISSION', 'FOND_GARANTIE', 'CODE_ASSURE', 'CODE_VALIDATION', 'CODE_MOTIF', 'OBSERVATION', 'CREE_PAR', 'id_APERITEUR_AFFAIRE', 'DATE_APERITEUR_AFFAIRE', 'id_ADRESSE_CLIENT', 'id_ADRESSE_ASSURE', 'ID', 'ID_AVENANT', 'ID_SOUS_BRANCHE', 'ID_DUREE', 'ID_AGENCE', 'CODE_DEVISE', 'COURS_DEVISE', 'CODE_COURS_DEVISE', 'PRIME_ANN_GBASE_DEVISE', 'PRIME_ANN_GANNEXE_DEVISE', 'FRAIS_ANN_DEVISE', 'TAXES_ANN_BASE_DEVISE', 'TAXES_ANN_ANNEXE_DEVISE', 'TAXES_ANN_DEVISE', 'PRIME_TOTAL_ANN_DEVISE', 'PRIME_COMPTANT_GBASE_DEVISE', 'PRIME_COMPTANT_GANNEXE_DEVISE', 'FRAIS_COMPTANT_DEVISE', 'TAXES_COMPTANT_BASE_DEVISE', 'TAXES_COMPTANT_ANNEXE_DEVISE', 'TAXES_COMPTANT_DEVISE', 'PRIME_TOTAL_COMPTANT_DEVISE', 'id_APERITEUR_AFFAIRE2', 'TAUX_RAPPORTEUR1', 'TAUX_RAPPORTEUR2', 'COMMISSION_APPORT_BASE_COMPTANT', 'COMMISSION_APPORT_ANNEXE_COMPTANT', 'COMMISSION_GESTION_BASE_COMPTANT', 'COMMISSION_GESTION_ANNEXE_COMPTANT', 'COMMISSION_APPORT_COMPTANT', 'COMMISSION_GESTION_COMPTANT'

-- Définir les colonnes recherchées
--DECLARE @Columns TABLE (ColumnName NVARCHAR(128));
--INSERT INTO @Columns (ColumnName) VALUES ('colonne1'), ('colonne2'), ('colonne3'), ('colonne4'), ('colonne5');

-- Trouver les objets qui contiennent toutes les colonnes recherchées
SELECT 
    o.name AS ObjectName,
    o.type_desc AS ObjectType
FROM 
    sys.columns c
JOIN 
    sys.objects o ON c.object_id = o.object_id
WHERE 
    o.type IN ('U', 'V') -- 'U' pour tables, 'V' pour vues
    AND c.name IN ('CODE_COMPAGNIE', 'CODE_AGENCE', 'NUMERO_POLICE', 'NOTE_COUVERTURE', 'CODE_BRANCHE', 'CODE_SOUS_BRANCHE', 'CODE_CLIENT', 'ASSURE', 'TYPE_TARIFICATION', 'CODE_AVENANT', 'NUM_AVNT_COURS', 'FRAIS', 'TAXES', 'DATE_SOUSCRIPTION_POLICE', 'DATE_EFFET_POLICE', 'DATE_SOUSCRIPTION', 'DATE_EFFET', 'DATE_ECHEANCE_PRINCIPALE', 'DATE_ECHEANCE_PROCHAINE', 'DATE_EXPIRATION', 'DATE_DERN_MAJ', 'DATE_COMPTANT_DU', 'DATE_COMPTANT_AU', 'CODE_FONCTIONNEMENT', 'TERME', 'CODE_FRACTIONNEMENT', 'COASSURANCE', 'TYPE_COASSURANCE', 'NBR_COASSUREURS', 'TAUX_COASSURANCE', 'FRAIS_COASSURANCE', 'TAUX_COMMISSION_DEROGATOIRE_BASE', 'TAUX_COMMISSION_DEROGATOIRE_ANNEXE', 'COMMISSION_BASE_ANN', 'COMMISSION_ANNEXE_ANN', 'COMMISSION_ANN', 'COMMISSION_BASE_COMPTANT', 'COMMISSION_ANNEXE_COMPTANT', 'COMMISSION_COMPTANT', 'PRIME_ANN_GBASE', 'PRIME_ANN_GANNEXE', 'FRAIS_ANN', 'TAXES_ANN_BASE', 'TAXES_ANN_ANNEXE', 'TAXES_ANN', 'PRIME_TOTAL_ANN', 'PRIME_COMPTANT_GBASE', 'PRIME_COMPTANT_GANNEXE', 'FRAIS_COMPTANT', 'TAXES_COMPTANT_BASE', 'TAXES_COMPTANT_ANNEXE', 'TAXES_COMPTANT', 'PRIME_TOTAL_COMPTANT', 'NUMERO_PROPOSITION', 'TYPE', 'NOM', 'PRENOM', 'RAISON_SOC', 'PAYS', 'VILLE', 'ADRESSE', 'CP_VILLE', 'TEL', 'GSM', 'FAX', 'E_MAIL', 'PROFESSION', 'SEC_ACTIVITE', 'CIN', 'REG_COMMERCE', 'CODE_TVA', 'ABREVIATION', 'RIB', 'CODE_CLIENT_RGP', 'CODE_NEW', 'VIP', 'IMMATRICULATION', 'MARQUE_VEHICULE', 'TYPE_VEHICULE', 'CODE_SUSPENTION', 'DATE_SUSPENTION', 'CODE_REM_VIGUEUR', 'DATE_REM_VIGUEUR', 'CODE_RESILIATION', 'DATE_RESILIATION', 'CODE_REM_COURS', 'DATE_REM_COURS', 'CODE_REASSURANCE', 'BONUS_MALUS', 'COMMISSION', 'FOND_GARANTIE', 'CODE_ASSURE', 'CODE_VALIDATION', 'CODE_MOTIF', 'OBSERVATION', 'CREE_PAR', 'id_APERITEUR_AFFAIRE', 'DATE_APERITEUR_AFFAIRE', 'id_ADRESSE_CLIENT', 'id_ADRESSE_ASSURE', 'ID', 'ID_AVENANT', 'ID_SOUS_BRANCHE', 'ID_DUREE', 'ID_AGENCE', 'CODE_DEVISE', 'COURS_DEVISE', 'CODE_COURS_DEVISE', 'PRIME_ANN_GBASE_DEVISE', 'PRIME_ANN_GANNEXE_DEVISE', 'FRAIS_ANN_DEVISE', 'TAXES_ANN_BASE_DEVISE', 'TAXES_ANN_ANNEXE_DEVISE', 'TAXES_ANN_DEVISE', 'PRIME_TOTAL_ANN_DEVISE', 'PRIME_COMPTANT_GBASE_DEVISE', 'PRIME_COMPTANT_GANNEXE_DEVISE', 'FRAIS_COMPTANT_DEVISE', 'TAXES_COMPTANT_BASE_DEVISE', 'TAXES_COMPTANT_ANNEXE_DEVISE', 'TAXES_COMPTANT_DEVISE', 'PRIME_TOTAL_COMPTANT_DEVISE', 'id_APERITEUR_AFFAIRE2', 'TAUX_RAPPORTEUR1', 'TAUX_RAPPORTEUR2', 'COMMISSION_APPORT_BASE_COMPTANT', 'COMMISSION_APPORT_ANNEXE_COMPTANT', 'COMMISSION_GESTION_BASE_COMPTANT', 'COMMISSION_GESTION_ANNEXE_COMPTANT', 'COMMISSION_APPORT_COMPTANT', 'COMMISSION_GESTION_COMPTANT')
GROUP BY 
    o.name, o.type_desc
HAVING 
    COUNT(DISTINCT c.name) = 131;

SELECT 
    TABLE_NAME AS ObjectName,
    TABLE_TYPE AS ObjectType
FROM 
    INFORMATION_SCHEMA.COLUMNS
WHERE 
    COLUMN_NAME IN ('CODE_COMPAGNIE', 'CODE_AGENCE', 'NUMERO_POLICE', 'NOTE_COUVERTURE', 'CODE_BRANCHE', 'CODE_SOUS_BRANCHE', 'CODE_CLIENT', 'ASSURE', 'TYPE_TARIFICATION', 'CODE_AVENANT', 'NUM_AVNT_COURS', 'FRAIS', 'TAXES', 'DATE_SOUSCRIPTION_POLICE', 'DATE_EFFET_POLICE', 'DATE_SOUSCRIPTION', 'DATE_EFFET', 'DATE_ECHEANCE_PRINCIPALE', 'DATE_ECHEANCE_PROCHAINE', 'DATE_EXPIRATION', 'DATE_DERN_MAJ', 'DATE_COMPTANT_DU', 'DATE_COMPTANT_AU', 'CODE_FONCTIONNEMENT', 'TERME', 'CODE_FRACTIONNEMENT', 'COASSURANCE', 'TYPE_COASSURANCE', 'NBR_COASSUREURS', 'TAUX_COASSURANCE', 'FRAIS_COASSURANCE', 'TAUX_COMMISSION_DEROGATOIRE_BASE', 'TAUX_COMMISSION_DEROGATOIRE_ANNEXE', 'COMMISSION_BASE_ANN', 'COMMISSION_ANNEXE_ANN', 'COMMISSION_ANN', 'COMMISSION_BASE_COMPTANT', 'COMMISSION_ANNEXE_COMPTANT', 'COMMISSION_COMPTANT', 'PRIME_ANN_GBASE', 'PRIME_ANN_GANNEXE', 'FRAIS_ANN', 'TAXES_ANN_BASE', 'TAXES_ANN_ANNEXE', 'TAXES_ANN', 'PRIME_TOTAL_ANN', 'PRIME_COMPTANT_GBASE', 'PRIME_COMPTANT_GANNEXE', 'FRAIS_COMPTANT', 'TAXES_COMPTANT_BASE', 'TAXES_COMPTANT_ANNEXE', 'TAXES_COMPTANT', 'PRIME_TOTAL_COMPTANT', 'NUMERO_PROPOSITION', 'TYPE', 'NOM', 'PRENOM', 'RAISON_SOC', 'PAYS', 'VILLE', 'ADRESSE', 'CP_VILLE', 'TEL', 'GSM', 'FAX', 'E_MAIL', 'PROFESSION', 'SEC_ACTIVITE', 'CIN', 'REG_COMMERCE', 'CODE_TVA', 'ABREVIATION', 'RIB', 'CODE_CLIENT_RGP', 'CODE_NEW', 'VIP', 'IMMATRICULATION', 'MARQUE_VEHICULE', 'TYPE_VEHICULE', 'CODE_SUSPENTION', 'DATE_SUSPENTION', 'CODE_REM_VIGUEUR', 'DATE_REM_VIGUEUR', 'CODE_RESILIATION', 'DATE_RESILIATION', 'CODE_REM_COURS', 'DATE_REM_COURS', 'CODE_REASSURANCE', 'BONUS_MALUS', 'COMMISSION', 'FOND_GARANTIE', 'CODE_ASSURE', 'CODE_VALIDATION', 'CODE_MOTIF', 'OBSERVATION', 'CREE_PAR', 'id_APERITEUR_AFFAIRE', 'DATE_APERITEUR_AFFAIRE', 'id_ADRESSE_CLIENT', 'id_ADRESSE_ASSURE', 'ID', 'ID_AVENANT', 'ID_SOUS_BRANCHE', 'ID_DUREE', 'ID_AGENCE', 'CODE_DEVISE', 'COURS_DEVISE', 'CODE_COURS_DEVISE', 'PRIME_ANN_GBASE_DEVISE', 'PRIME_ANN_GANNEXE_DEVISE', 'FRAIS_ANN_DEVISE', 'TAXES_ANN_BASE_DEVISE', 'TAXES_ANN_ANNEXE_DEVISE', 'TAXES_ANN_DEVISE', 'PRIME_TOTAL_ANN_DEVISE', 'PRIME_COMPTANT_GBASE_DEVISE', 'PRIME_COMPTANT_GANNEXE_DEVISE', 'FRAIS_COMPTANT_DEVISE', 'TAXES_COMPTANT_BASE_DEVISE', 'TAXES_COMPTANT_ANNEXE_DEVISE', 'TAXES_COMPTANT_DEVISE', 'PRIME_TOTAL_COMPTANT_DEVISE', 'id_APERITEUR_AFFAIRE2', 'TAUX_RAPPORTEUR1', 'TAUX_RAPPORTEUR2', 'COMMISSION_APPORT_BASE_COMPTANT', 'COMMISSION_APPORT_ANNEXE_COMPTANT', 'COMMISSION_GESTION_BASE_COMPTANT', 'COMMISSION_GESTION_ANNEXE_COMPTANT', 'COMMISSION_APPORT_COMPTANT', 'COMMISSION_GESTION_COMPTANT')
GROUP BY 
    TABLE_NAME, TABLE_TYPE
HAVING 
    COUNT(DISTINCT COLUMN_NAME) = 131;





-- Rechercher des colonnes dans les tables
SELECT
'Table' AS ObjectType,
t.name AS ObjectName,
c.name AS ColumnName
FROM
sys.columns c
JOIN
sys.tables t ON c.object_id = t.object_id
WHERE
c.name IN ('COMMISSION_GESTION_COMPTANT', 'MARQUE_VEHICULE', 'CODE_BRANCHE', 'CODE_SOUS_BRANCHE')

UNION ALL

-- Rechercher des colonnes dans les vues
SELECT
'View' AS ObjectType,
v.name AS ObjectName,
c.name AS ColumnName
FROM
sys.columns c
JOIN
sys.views v ON c.object_id = v.object_id
WHERE
c.name IN ('COMMISSION_GESTION_COMPTANT', 'MARQUE_VEHICULE', 'CODE_BRANCHE', 'CODE_SOUS_BRANCHE', 'CODE_AVENANT')

UNION ALL

-- Rechercher des colonnes dans les procédures stockées et les fonctions
SELECT
'Stored Procedure/Function' AS ObjectType,
OBJECT_NAME(object_id) AS ObjectName,
NULL AS ColumnName
FROM
sys.sql_modules
WHERE
definition IN ('COMMISSION_GESTION_COMPTANT', 'MARQUE_VEHICULE', 'CODE_BRANCHE', 'CODE_SOUS_BRANCHE');